Models/PuchaseMaterials.cs
namespace Практика.Models
{
    public class PuchaseMaterials
    {
        public int Id { get; set; }
        public string Material {  get; set; }
        public int MaterialId { get; set; }
        public double Count { get; set; }
        public double Price { get; set; }
        public DateTime Date { get; set; }
        public string Employee {  get; set; }
        public int EmployeeId { get; set; }
    }
}

Controllers/PuchaseMaterialsController.cs
using Microsoft.AspNetCore.Mvc;
using Практика.Models;
using Microsoft.Data.SqlClient;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Data;
namespace Практика.Controllers
{
    public class PuchaseMaterialsController : Controller
    {
        private string connectionString = "Server=DESKTOP-9P53NEF\\SQLEXPRESS;Database=БД_СУБД;Trusted_Connection=True;TrustServerCertificate=True";
        public IActionResult Index()
        {
            List<PuchaseMaterials> puchaseMaterials = new List<PuchaseMaterials>();
            using (SqlConnection connection = new SqlConnection(connectionString))
            {
                connection.Open();
                string query = "SELECT p.ID,m.name,p.count,p.price,p.date,e.name FROM Purchase_materials p " +
                    "JOIN Materials m ON p.material=m.ID " +
                    "JOIN Employees e ON p.employee=e.ID";
                using (SqlCommand command = new SqlCommand(query, connection))
                using (SqlDataReader reader = command.ExecuteReader())
                {
                    while (reader.Read())
                    {
                        puchaseMaterials.Add(new PuchaseMaterials
                        {
                            Id = reader.GetInt32(0),
                            Material = reader.GetString(1),
                            Count = reader.GetDouble(2),
                            Price = reader.GetDouble(3),
                            Date = reader.GetDateTime(4),
                            Employee = reader.GetString(5)
                        });
                    }
                }
            }
            ViewBag.Budget = GetBudget();
            return View(puchaseMaterials.OrderByDescending(p => p.Id).Take(5).ToList());
        }
        public IActionResult Delete(int id)
        {
            using (SqlConnection connection = new SqlConnection(connectionString))
            {
                connection.Open();
                string query = "DELETE FROM Purchase_materials WHERE ID=@Id";
                using (SqlCommand command = new SqlCommand(query, connection))
                {
                    command.Parameters.AddWithValue("@Id", id);
                    command.ExecuteNonQuery();
                }
            }
            return RedirectToAction("Index");
        }
        public IActionResult Insert()
        {
            ViewBag.Materials = GetMaterials();
            ViewBag.Employees = GetEmployees();
            ViewBag.Budget = GetBudget();
            return View(new PuchaseMaterials());
        }
        [HttpPost]
        public IActionResult Insert(PuchaseMaterials puchase)
        {
            double budget = GetBudget();
            if (puchase.Price > budget)
            {
                ViewBag.Materials = GetMaterials();
                ViewBag.Employees = GetEmployees();
                ViewBag.Budget = GetBudget();
                TempData["ErrorMessage"] = "Не хватает бюджета для покупки";
                return View("Insert", puchase);
            }
            using (SqlConnection connection = new SqlConnection(connectionString))
            {
                connection.Open();
                string query = "INSERT INTO Purchase_materials(material,count,price,date,employee) VALUES(@material,@count,@price,@date,@employee)";
                Console.WriteLine($"дата {puchase.Date}");
                using (SqlCommand command = new SqlCommand(query, connection))
                {
                    command.Parameters.AddWithValue("@material", puchase.MaterialId);
                    command.Parameters.AddWithValue("@count", puchase.Count);
                    command.Parameters.AddWithValue("@price", puchase.Price);
                    command.Parameters.AddWithValue("@date", puchase.Date);
                    command.Parameters.AddWithValue("@employee", puchase.EmployeeId);
                    command.ExecuteNonQuery();
                }
                string updateMaterial = "UPDATE Materials SET count=count+@count, cost=cost+@cost WHERE ID=@Id";
                using (SqlCommand command = new SqlCommand(updateMaterial, connection))
                {
                    command.Parameters.AddWithValue("@count", puchase.Count);
                    command.Parameters.AddWithValue("@cost", puchase.Price);
                    command.Parameters.AddWithValue("@Id", puchase.MaterialId);
                    command.ExecuteNonQuery();
                }
                string updateBudget = "UPDATE Budget SET budget=budget-@budget WHERE ID=1";
                using (SqlCommand command = new SqlCommand(updateBudget, connection))
                {
                    command.Parameters.AddWithValue("@budget", puchase.Price);
                    command.ExecuteNonQuery();
                }
            }
            return RedirectToAction("Index");
        }
        public IActionResult Edit(int id)
        {
            PuchaseMaterials puchase = null;
            using (SqlConnection connection = new SqlConnection(connectionString))
            {
                connection.Open();
                string query = "SELECT ID, material,count,price,date,employee FROM Purchase_materials WHERE ID=@Id";
                using (SqlCommand command = new SqlCommand(query, connection))
                {
                    command.Parameters.AddWithValue("@Id", id);
                    using (SqlDataReader reader = command.ExecuteReader())
                    {
                        while (reader.Read())
                        {
                            puchase = new PuchaseMaterials
                            {
                                Id = reader.GetInt32(0),
                                MaterialId = reader.GetInt32(1),
                                Count = reader.GetDouble(2),
                                Price = reader.GetDouble(3),
                                Date = reader.GetDateTime(4),
                                EmployeeId = reader.GetInt32(5)
                            };
                        }
                    }
                }
            }
            ViewBag.Materials = GetMaterials();
            ViewBag.Employees = GetEmployees();
            return View(puchase);
        }
        [HttpPost]
        public IActionResult Edit(PuchaseMaterials puchase)
        {
            double price = 0, count = 0, budget = GetBudget();
            using (SqlConnection connection = new SqlConnection(connectionString))
            {
                connection.Open();
                string getInfoMaterial = "SELECT count, price FROM Purchase_materials WHERE ID=@Id";
                using (SqlCommand command = new SqlCommand(getInfoMaterial, connection))
                {
                    command.Parameters.AddWithValue("@Id", puchase.Id);
                    using (SqlDataReader reader = command.ExecuteReader())
                    {
                        if (reader.Read())
                        {
                            count = reader.GetDouble(0);
                            price = reader.GetDouble(1);
                        }
                    }
                }

                if (puchase.Price > price || puchase.Price < price)
                {
                    if (puchase.Price > budget)
                    {
                        ViewBag.Materials = GetMaterials();
                        ViewBag.Employees = GetEmployees();
                        TempData["ErrorMessage"] = "Не хватает бюджета для этой покупки";
                        return RedirectToAction("Edit", puchase);

                    }
                }
                string query = "UPDATE Materials SET count=count-@oldcount+@newcount, cost=cost-@oldprice+@newprice WHERE ID=@Id";
                using (SqlCommand command = new SqlCommand(query, connection))
                {
                    command.Parameters.AddWithValue("@Id", puchase.MaterialId);
                    command.Parameters.AddWithValue("@oldcount", count);
                    command.Parameters.AddWithValue("@newcount", puchase.Count);
                    command.Parameters.AddWithValue("@oldprice", price);
                    command.Parameters.AddWithValue("@newprice", puchase.Price);
                    command.ExecuteNonQuery();
                }
                if (puchase.Price > price || puchase.Price < price)
                {
                    string updateBudget = "UPDATE Budget SET budget=budget+@oldprice-@newprice WHERE ID=1";
                    using(SqlCommand command = new SqlCommand(updateBudget, connection))
                    {
                        command.Parameters.AddWithValue("@oldprice", price);
                        command.Parameters.AddWithValue("@newprice",puchase.Price);
                        command.ExecuteNonQuery();
                    }
                }
                string updatePurchase = "UPDATE Purchase_materials SET material=@material, count=@count, price=@price, date=@date, employee=@employee WHERE ID=@Id";
                using(SqlCommand command = new SqlCommand(updatePurchase, connection))
                {
                    command.Parameters.AddWithValue("@material",puchase.MaterialId);
                    command.Parameters.AddWithValue("@count",puchase.Count);
                    command.Parameters.AddWithValue("@price",puchase.Price);
                    command.Parameters.AddWithValue("@date",puchase.Date);
                    command.Parameters.AddWithValue("@employee",puchase.EmployeeId);
                    command.Parameters.AddWithValue("@Id",puchase.Id);
                    command.ExecuteNonQuery();
                }
            }
            return RedirectToAction("Index");
        }
        public List<SelectListItem> GetMaterials()
        {
            List<SelectListItem> materials = new List<SelectListItem>();
            using (SqlConnection connection = new SqlConnection(connectionString))

Views/PuchaseMaterials/Edit.cshtml
@model Практика.Models.PuchaseMaterials
@{
    var materials = ViewBag.Materials as List<SelectListItem>;
    var employees = ViewBag.Employees as List<SelectListItem>;
}
<div class="conteiner">
    <h1 style="text-align:center;">Редоктирование</h1>
   <form method="post" action="Edit">
       <input type="hidden" asp-for="Id" />
       <label>Материал</label>
       <select asp-for="MaterialId" asp-items="@materials"></select>
       <label>Количество</label>
       <input type="text" asp-for="Count" />
       <label>Цена</label>
       <input type="text" asp-for="Price" />
       <label>Дата</label>
       <input type="date" asp-for="Date" />
        <label>Сотрудник</label>
        <select asp-for="EmployeeId" asp-items="@employees"></select>
        <div class="action">
            <button type="submit" class="btn_add">Обновить</button>
            <a href="@Url.Action("Index","PuchaseMaterials")" class="btn_back">Вернуться</a>
        </div>
   </form>
</div>
<style>
    body{
        font-family: 'Trebuchet MS', 'Lucida Sans Unicode', 'Lucida Grande', 'Lucida Sans', Arial, sans-serif;
        background-color:beige;
        margin: 0;
        padding: 0;
    }
    .conteiner{
        width: 60%;
        margin: 60px auto;
        background-color: antiquewhite;
        border-radius: 10px;
        box-shadow: 0 4px 8px rgba(0,0,0,0.1);
    }
    form{
        display: flex;
        flex-direction: column;
        text-align: center;
        padding: 12px;
        width: 50%;
        margin: 15px auto;
    }
    select, input{
        padding: 12px;
        border:none;
        border-radius: 5px;
        box-shadow: 0 2px 4px rgba(0,0,0,0.1);
        font-size: 16px;
        margin-bottom: 10px;
    }
    label{
        margin-bottom: 10px;
        font-size: 18px;
        text-align: left;
    }
    .action{
        display: flex;
        justify-content: safe center;
        gap: 10px;
        margin-top: 10px;
    }
    .btn_add{
        padding: 12px;
        font-size: 16px;
        border:none;
        border-radius: 5px;
        box-shadow: 0 2px 4px rgba(0,0,0,0.1);
    }
    .btn_back{
        padding: 12px;
        font-size: 16px;
        border: none;
        border-radius: 5px;
        box-shadow: 0 2px 4px rgba(0,0,0,0.1);
        text-decoration: none;
        color: black;
        background-color: #f0f0f0;
    }
</style>

Views/PuchaseMaterials/Index.cshtml
@model List<Практика.Models.PuchaseMaterials>
@{
    var user = Context.Session.GetInt32("Role");
}
<div class="conteiner">
    <h1>Закупка сырья</h1>
    <div class="action">
        @if (user == 3 || user == 13)
        {
            <a href="@Url.Action("Insert","PuchaseMaterials")" class="btn_buy">Купить сырье</a>
        }
        else
        {
            <a href="javascript:void(0)" class="btn_none">Купить сырье</a>
        }
        <a href="@Url.Action("Index","Home")" class="btn_back">Вернуться</a>
    </div>
    <div style="display:flex;justify-content:left;">Бюджет: <span>@ViewBag.Budget.ToString("N2")</span></div>
    <table>
        <thead>
            <tr>
                <th>Материал</th>
                <th>Количество</th>
                <th>Цена</th>
                <th>Дата</th>
                <th>Сотрудник</th>
                <th>Действие</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var purchase in Model)
            {
                <tr>
                    <td>@purchase.Material</td>
                    <td>@purchase.Count</td>
                    <td>@purchase.Price</td>
                    <td>@purchase.Date.ToString("yyyy-mm-dd")</td>
                    <td>@purchase.Employee</td>
                    <td>
                        <div class="action">
                            @if (user == 3 || user == 13)
                            {
                                <form method="post" action="/PuchaseMaterials/Delete/@purchase.Id" onsubmit="return confirm('Вы уверены что хотите удалить?')">
                                    <button class="btn_del">Удалить</button>
                                </form>
                                <form action="/PuchaseMaterials/Edit/@purchase.Id">
                                    <button class="btn_ed">Редоктировать</button>
                                </form>
                            }
                            else{
                                <form>
                                    <button type="button" class="btn_none" disabled>Удалить</button>
                                </form>
                                <form>
                                    <button type="button" class="btn_none" disabled>Редоктировать</button>
                                </form>
                            }
                        </div>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

<style>
    body {
        font-family: 'Trebuchet MS', 'Lucida Sans Unicode', 'Lucida Grande', 'Lucida Sans', Arial, sans-serif;
        background-color: beige;
        margin: 0;
        padding: 0;
    }

    .conteiner {
        width: 60%;
        padding: 20px;
        text-align: center;
        background-color: azure;
        border-radius: 10px;
        box-shadow: 0 4px 8px rgba(0,0,0,0.1);
        margin: 60px auto;
    }

    table {
        width: 100%;
        margin: 0 auto;
        text-align: center;
    }

        table th, table td {
            padding: 12px;
            font-size: 17px;
            border: 1px solid gray;
        }

        table th {
            background-color: beige;
        }

    .action {
        display: flex;
        justify-content: center;
        gap: 10px;
        margin-bottom: 10px;
    }

    .btn_del {
        background-color: red;
        padding: 12px;
        border: none;
        border-radius: 5px;
        color: white;
    }

    .btn_ed {
        background-color: green;
        padding: 12px;
        border: none;
        border-radius: 5px;
        color: white;
    }

    a {
        padding: 12px;
        width: 20%;
        text-decoration: none;
        border-radius: 5px;
        color: white;
        background-color: blue;
    }

    .btn_none {
        padding: 12px;
        text-decoration: none;
        border-radius: 5px;
        background-color: gray;
        color: white;
        border: none;
        cursor: no-drop;
    }
</style>

Views/PuchaseMaterials/Insert.cshtml
@model Практика.Models.PuchaseMaterials
@{
    var materialsList = ViewBag.Materials as List<SelectListItem>;
    var employeesList = ViewBag.Employees as List<SelectListItem>;
    var dateValue = Model.Date == default ? DateTime.Now.ToString("yyyy-MM-dd") : Model.Date.ToString("yyyy-MM-dd");

}
<div class="conteiner">
    <h1>Покупка сырья</h1>
    @if (TempData["ErrorMessage"] != null){
        <div style="color:red;">
            @TempData["ErrorMessage"]
        </div>
    }

    <form method="post" asp-action="Insert">
        <label>Сырье</label>
        <select asp-for="MaterialId">
            <option>Выберите сырье</option>
            @foreach (var material in materialsList)
            {
                <option value="@material.Value">@material.Text</option>
            }
        </select>
        <label>Количество</label>
        <input type="text" asp-for="Count"  required />
        <label>Цена</label>
        <input type="text" asp-for="Price"  required />
        <label>Дата</label>
        <input type="date" asp-for="Date" value="@dateValue" required />
        <label>Сотрудник</label>
        <select asp-for="EmployeeId">
            <option>Выберите сотрудника</option>
            @foreach (var employee in employeesList)
            {
                <option value="@employee.Value">@employee.Text</option>
            }
        </select>
        <div class="action">
            <button type="submit" class="btn_add">Добавить</button>
            <a href="@Url.Action("Index","PuchaseMaterials")" class="btn_back">Вернуться</a>
        </div>
    </form>
</div>

<style>
    body {
        font-family: 'Trebuchet MS', 'Lucida Sans Unicode', 'Lucida Grande', 'Lucida Sans', Arial, sans-serif;
        background-color: burlywood;
        margin: 0;
        padding: 0;
    }

    .conteiner {
        padding: 20px;
        text-align: center;
        width: 60%;
        margin: 60px auto;
        background-color: bisque;
        box-shadow: 0 4px 8px rgba(0,0,0,0.1);
        border-radius: 10px;
    }

    form {
        display: flex;
        flex-direction: column;
        width: 50%;
        margin: 15px auto;
    }
    select, input{
        padding: 12px;
        border: none;
        border-radius: 5px;
        font-size: 16px;
        margin-bottom: 10px;
    }
    label{
        font-size: 18px;
        margin-bottom: 10px;
    }
    .btn_add{
        padding: 12px;
        border-radius:5px;
        border: none;
    }

    .btn_back {
        padding: 12px;
        border-radius: 5px;
        text-decoration: none;
        color: black;
        background-color: lightgray;   
    }
</style>