Controllers/BudgetController.cs
using Microsoft.AspNetCore.Mvc;
using Практика.Models;
using Microsoft.Data.SqlClient;
using System.Data;
using Microsoft.AspNetCore.Mvc.Rendering;
namespace Практика.Controllers
{
    public class BudgetController : Controller
    {
        public string connectionString = "Server=DESKTOP-9P53NEF\\SQLEXPRESS;DataBase=БД_СУБД;Trusted_Connection=True;TrustServerCertificate=True;";
        public IActionResult Index()
        {
            List<BudgetModel> budgets = new List<BudgetModel>();
            using (SqlConnection connection = new SqlConnection(connectionString))
            {
                connection.Open();
                string query = "SELECT ID,budget,bonus, Precent FROM Budget";
                using (SqlCommand command = new SqlCommand(query, connection))
                {
                    using (SqlDataReader reader = command.ExecuteReader())
                    {
                        while (reader.Read())
                        {
                            var item = new BudgetModel
                            {
                                Id = reader.GetInt32(0),
                                Budget = Math.Round(reader.GetDouble(1), 2),
                                Bonus = Math.Round(reader.GetDouble(2), 2),
                                Percent = Math.Round(reader.GetDouble(3), 2),
                            };
                            budgets.Add(item);
                        }
                    }
                }

            }
            return View(budgets);
        }
        public IActionResult Edit(int id)
        {
            BudgetModel budget = null;
            using (SqlConnection connection = new SqlConnection(connectionString))
            {
                connection.Open();
                string query = "SELECT ID,budget,bonus, Precent FROM Budget WHERE ID=@Id";
                using (SqlCommand command = new SqlCommand(query, connection))
                {
                    command.Parameters.AddWithValue("@Id", id);
                    using (SqlDataReader reader = command.ExecuteReader())
                    {
                        if (reader.Read())
                        {
                            budget = new BudgetModel
                            {
                                Id = reader.GetInt32(0),
                                Budget = Math.Round(reader.GetDouble(1), 2),
                                Bonus = Math.Round(reader.GetDouble(2), 2),
                                Percent = Math.Round(reader.GetDouble(3), 2),
                            };
                        }
                    }
                }
            }
            return View(budget);
        }
        [HttpPost]
        public IActionResult Edit(double Budget,double Bonus,double Percent,int Id)
        {
            using (SqlConnection connection = new SqlConnection(connectionString))
            {
                connection.Open();
                string query = "UPDATE Budget SET budget=@Budget, Precent=@Percent, bonus=@Bonus WHERE ID=@Id";
                Console.WriteLine($"{Budget}{Percent}{Bonus}{Id}");
                using (SqlCommand command = new SqlCommand(query, connection))
                {
                    command.Parameters.AddWithValue("@Budget", Budget);
                    command.Parameters.AddWithValue("@Percent", Percent);
                    command.Parameters.AddWithValue("@Bonus", Bonus);
                    command.Parameters.AddWithValue("@Id", Id);
                    command.ExecuteNonQuery();
                }
            }
            return RedirectToAction("Index");
        }

    }
}

Controllers/CreditController.cs
using Microsoft.AspNetCore.Mvc;
using Практика.Models;
using Microsoft.Data.SqlClient;
using System.Data;
namespace Практика.Controllers
{
    public class CreditController : Controller
    {
        private string connectionString = "Server=DESKTOP-9P53NEF\\SQLEXPRESS;DataBase=БД_СУБД;Trusted_Connection=True;TrustServerCertificate=True;";
        public IActionResult Index()
        {
            List<Credit> credit = new List<Credit>();
            using (SqlConnection connection = new SqlConnection(connectionString))
            {
                connection.Open();
                using (SqlCommand command = new SqlCommand("CreditInfo", connection))
                {
                    command.CommandType = CommandType.StoredProcedure;
                    using(SqlDataReader reader = command.ExecuteReader())
                    {
                        while (reader.Read())
                        {
                            credit.Add(new Credit
                            {
                                Id = reader.GetInt32(0),
                                Summa = reader.GetDouble(1),
                                Year = reader.GetInt32(2),
                                Precent = reader.GetDouble(3),
                                Fine = reader.GetDouble(4),
                                Date = reader.GetDateTime(5),
                                Description = reader.GetString(6)
                            });
                           
                        }
                    }
                }
            }
            return View(credit);
        }
        public IActionResult Delete(int id)
        {
            using(SqlConnection connection = new SqlConnection(connectionString))
            {
                connection.Open();
                string query = "DELETE FROM Credit WHERE ID=@Id";
                using(SqlCommand command = new SqlCommand(query, connection)) 
                {
                    command.Parameters.AddWithValue("@Id", id);
                    command.ExecuteNonQuery();
                }
            }
            return RedirectToAction("Index");
        }
        public IActionResult Insert()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Insert(Credit credit)
        {
            using (SqlConnection connection = new SqlConnection(connectionString))
            {
                connection.Open();
                using(SqlCommand command = new SqlCommand("AddCredit",connection))
                {
                    command.CommandType = CommandType.StoredProcedure;
                    command.Parameters.AddWithValue("@Summa", credit.Summa);
                    command.Parameters.AddWithValue("@Year", credit.Year);
                    command.Parameters.AddWithValue("@Percent", credit.Precent);
                    command.Parameters.AddWithValue("@Fine", credit.Fine);
                    command.Parameters.AddWithValue("@Date", credit.Date);
                    command.Parameters.AddWithValue("@Description", credit.Description);
                    command.ExecuteNonQuery();
                }
            }
            return RedirectToAction("Index");
        }
    }
}

Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Практика.Models;

namespace Практика.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/SalaryController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Data;
using Microsoft.Data.SqlClient;
using System.Globalization;
using Практика.Models;
namespace Практика.Controllers
{
    public class SalaryController : Controller
    {
        private string connectionString = "Server=DESKTOP-9P53NEF\\SQLEXPRESS;DataBase=БД_СУБД;Trusted_Connection=True;TrustServerCertificate=True;";
        public IActionResult Index(Salary salary)
        {
            List<Salary> salaryList = new List<Salary>();
            double total_Sum = 0;
            using (SqlConnection connection = new SqlConnection(connectionString))
            {
                connection.Open();
                using (SqlCommand command = new SqlCommand("CalculateSalary", connection))
                {
                    command.CommandType = CommandType.StoredProcedure;
                    if (salary.Year > 0 && salary.Month > 0)
                    {
                        command.Parameters.AddWithValue("@Year", salary.Year);
                        command.Parameters.AddWithValue("@Month", salary.Month);
                        using (SqlDataReader reader = command.ExecuteReader())
                        {
                            while (reader.Read())
                            {
                                salaryList.Add(new Salary
                                {
                                    Id = reader.GetInt32(0),
                                    Employee = reader.GetString(1),
                                    BaseSalary = reader.GetDouble(2),
                                    PurchaseCount = reader.GetInt32(3),
                                    ProductionCount = reader.GetInt32(4),
                                    SaleCount = reader.GetInt32(5),
                                    TotalCount = reader.GetInt32(6),
                                    Bonus = reader.GetDouble(7),
                                    TotalSalary = reader.GetDouble(8),
                                    PayStatus = reader.GetBoolean(9) ? "выплачено" : "невыплачено",
                                });
                            }
                            if (reader.NextResult() && reader.Read())
                            {
                                total_Sum = reader.GetDouble(0);
                            }
                        }
                    }

                }

            }
            TempData["Year"] = salary.Year;
            TempData["Month"] = salary.Month;
            ViewBag.Years = GetYear();
            ViewBag.Months = GetMonth();
            ViewBag.Total_Sum = total_Sum;
            return View(salaryList);
        }
        public IActionResult Edit(int id)
        {
            Salary salary = null;
            using (SqlConnection connection = new SqlConnection(connectionString))
            {
                connection.Open();
                using (SqlCommand command = new SqlCommand("EditSalary", connection))
                {
                    command.CommandType = CommandType.StoredProcedure;
                    command.Parameters.AddWithValue("@Id", id);
                    command.Parameters.AddWithValue("@Total_salary", DBNull.Value);
                    using (SqlDataReader reader = command.ExecuteReader())
                    {
                        while (reader.Read())
                        {
                            salary = new Salary
                            {
                                Id = reader.GetInt32(0),
                                Employee = reader.GetString(1),
                                TotalSalary = reader.GetDouble(2),
                                Year = reader.GetInt32(3),
                                Month = reader.GetInt32(4)
                            };
                        }

                    }
                }
            }
            return View(salary);
        }
        [HttpPost]
        public IActionResult Edit(Salary salary)
        {
            using (SqlConnection connection = new SqlConnection(connectionString))
            {
                connection.Open();
                using (SqlCommand command = new SqlCommand("EditSalary", connection))
                {
                    command.CommandType = CommandType.StoredProcedure;
                    command.Parameters.AddWithValue("@Total_salary", salary.TotalSalary);
                    command.Parameters.AddWithValue("@Id", salary.Id);
                    command.ExecuteNonQuery();
                }
            }
            TempData["Year"] = salary.Year;
            TempData["Month"] = salary.Month;
            return RedirectToAction("Index", new { Year = TempData["Year"], Month = TempData["Month"] });
        }
        [HttpPost]
        public IActionResult PaySalaries(Salary salary)
        {
            
            try
            {
                using (SqlConnection connection = new SqlConnection(connectionString))
                {
                    connection.Open();
                    using (SqlCommand command = new SqlCommand("PaySalaries", connection))
                    {
                        command.CommandType = CommandType.StoredProcedure;
                            Console.WriteLine($"year {salary.Year} month {salary.Month}");
                        if(salary.Year > 0 &&  salary.Month > 0)
                        {
                            command.Parameters.AddWithValue("@Year", salary.Year);
                            command.Parameters.AddWithValue("@Month", salary.Month);
                            command.ExecuteNonQuery();
                        }
                       
                    }
                }
            }
            catch (SqlException ex)
            {
                TempData["Error"] = ex.Message;
            }
           
            TempData["Year"] = salary.Year;
            TempData["Month"] = salary.Month;
            return RedirectToAction("Index", new { Year = TempData["Year"], Month = TempData["Month"] });
        }
        private List<SelectListItem> GetYear()
        {
            List<SelectListItem> year = new List<SelectListItem>();
            for (int i = 2024; i <= 2030; i++)
            {
                year.Add(new SelectListItem
                {
                    Value = i.ToString(),
                    Text = i.ToString()
                });
            }
            return year;
        }
        private List<SelectListItem> GetMonth()
        {
            List<SelectListItem> month = new List<SelectListItem>();
            string[] monthName = { "Январь", "Февраль", "Март", "Апрель", "Май", "Июнь", "Июль", "Август", "Сентябрь", "Октябрь", "Ноябрь", "Декабрь" };
            for (int i = 0; i < monthName.Length; i++)
            {
                month.Add(new SelectListItem
                {
                    Value = (i + 1).ToString(),
                    Text = monthName[i].ToString()
                });
            }
            return month;
        }
    }
}

Views/Home/Index.cshtml
@{
    Layout = "_Layout";  // Используем общий Layout
    var user = Context.Session.GetInt32("Role");
}
<style>
    body {
        font-family: Arial, Helvetica, sans-serif;
        background-color: lightyellow;
        color: #333;
        margin: 0;
        padding: 0;
    }

    .conteiner {
        width: 50%;
        margin: 50px auto;
        padding: 20px;
        background-color: white;
        border-radius: 8px;
        text-align: center;
        box-shadow: 4px 4px 8px rgba(0,0,0,0.1);
    }

    .btn_primary {
        color: white;
        background-color: darkslategray;
        border: none;
        padding: 15px 0;
        font-size: 18px;
        border-radius: 5px;
        text-decoration: none; /*убирает черточки например у ссылок снизу*/
        cursor: pointer; /*делает курсор в виде руки*/
        margin: 10px;
        width: 25%;
        transition: all 0.2s ease-in-out;
    }

        .btn_primary:hover {
            transform: scale(1.1);
            box-shadow: 0 4px 8px rgba(0,0,0,0.1);
            background-color: green;
            color: white;
        }

        .btn_primary:hover {
            background-color: green; /*при наведении на кнопку меняеться цвет*/
        }

    .btn_none {
        color: white;
        background-color: gray;
        border: none;
        padding: 15px 0;
        font-size: 18px;
        border-radius: 5px;
        text-decoration: none; /*убирает черточки например у ссылок снизу*/
        cursor: pointer; /*делает курсор в виде руки*/
        margin: 10px;
        width: 25%;
        cursor: no-drop;
    }

    .options {
        display: flex; /*делает кнопки в ряд*/
        justify-content: safe center; /*сохраняет кнопки по центру*/
        flex-wrap: nowrap; /*не переносит кнопки ссылки на новую строку*/
    }
</style>
<div class="conteiner">
    <h1 class="text">Кафе</h1>
    <p>Выберите действие</p>
    <div class="options">
        @if (user == 2 || user == 3 || user == 11)
        {

            <a href="@Url.Action("Index", "Product")" class="btn_primary">Продукты</a>
            <a href="@Url.Action("Index", "Materials")" class="btn_primary">Сырье</a>
            <a href="@Url.Action("Index", "Ingredients")" class="btn_primary">Ингредиенты</a>
        }
        else
        {
            <a href="javascript:void(0)" class="btn_none">Продукты</a>
            <a href="javascript:void(0)" class="btn_none">Сырье</a>
            <a href="javascript:void(0)" class="btn_none">Ингредиенты</a>
        }
    </div>
    <div class="options">
        @if (user == 2 || user == 3 || user == 11)
        {
            <a href="@Url.Action("Index", "Production")" class="btn_primary">Производство</a>

        }
        else
        {
            <a href="javascript:void(0)" class="btn_none">Производство</a>
        }
        @if (user == 13 || user == 3 || user == 11)
        {
            <a href="@Url.Action("Index", "PuchaseMaterials")" class="btn_primary">Закупка сырья</a>
            <a href="@Url.Action("Index", "SaleProducts")" class="btn_primary">Продажа</a>
        }
        else
        {
            <a href="javascript:void(0)" class="btn_none">Закупка сырья</a>
            <a href="javascript:void(0)" class="btn_none">Продажа</a>
        }
    </div>
    <div class="options">
        @if (user == 11 || user == 3)
        {
            <a href="@Url.Action("Index", "Salary")" class="btn_primary">Зарплата</a>
        }
        else
        {
            <a href="javascript:void(0)" class="btn_none">Зарплата</a>
        }
        @if (user == 3 || user == 12 || user == 11)
        {
            <a href="@Url.Action("Index", "Credit")" class="btn_primary">Кредит</a>
            <a href="@Url.Action("Index", "PayCredit")" class="btn_primary">Оплата за кредит</a>
        }
        else
        {

            <a href="javascript:void(0)" class="btn_none">Кредит</a>
            <a href="javascript:void(0)" class="btn_none">Оплата за кредит</a>
        }
    </div>
    <div class="options">
        @if (user == 3 || user == 11)
        {
            <a href="@Url.Action("Index", "Employees")" class="btn_primary">Сотрудники</a>
        }
        else
        {
            <a href="javascript:void(0)" class="btn_none">Сотрудники</a>
        }
        <a href="@Url.Action("Index", "Authorization")" class="btn_primary">Выйти</a>
        @if (user == 3 || user == 12 || user == 11)
        {
            <a href="@Url.Action("Index", "Budget")" class="btn_primary">Бюджет</a>
        }
        else
        {
            <a href="javascript:void(0)" class="btn_none">Сотрудники</a>
        }
    </div>
</div>