Models/Materials.cs
namespace Практика.Models
{
    public class Materials
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int UnitId { get; set; }
        public string Unit {  get; set; }
        public double Count { get; set; }
        public double Cost { get; set; }
    }
}

Controllers/MaterialsController.cs
using Microsoft.AspNetCore.Mvc;
using Практика.Models;
using Microsoft.Data.SqlClient;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace Практика.Controllers
{
    public class MaterialsController : Controller
    {
        private string connectionString = "Server=DESKTOP-9P53NEF\\SQLEXPRESS;Database=БД_СУБД;Trusted_Connection=True;TrustServerCertificate=True";
        public IActionResult Index()
        {
            List<Materials> materials = new List<Materials>();
            using (SqlConnection connection = new SqlConnection(connectionString))
            {
                connection.Open();
                string query = "SELECT m.ID,m.name, u.name,m.count,m.cost FROM Materials m " +
                    "JOIN UnitsOfMeasurement u ON m.unitOfMeasurement = u.ID";
                using (SqlCommand command = new SqlCommand(query, connection))
                using (SqlDataReader reader = command.ExecuteReader())
                {
                    while (reader.Read())
                    {
                        materials.Add(new Materials
                        {
                            Id = reader.GetInt32(0),
                            Name = reader.GetString(1),
                            Unit = reader.GetString(2),
                            Count = Math.Round(reader.GetDouble(3), 2),
                            Cost = Math.Round(reader.GetDouble(4), 2)
                        });
                    }
                }
            }
            return View(materials);
        }

        [HttpPost]
        public IActionResult Delete(int id)
        {
            using (SqlConnection connection = new SqlConnection(connectionString))
            {
                connection.Open();
                string query = "DELETE FROM Materials WHERE ID=@Id";
                using (SqlCommand command = new SqlCommand(query, connection))
                {
                    command.Parameters.AddWithValue("@Id", id);
                    command.ExecuteNonQuery();
                }
            }
            return RedirectToAction("Index");
        }

        public IActionResult Insert()
        {
            ViewBag.Units = GetUnits();
            return View(new Materials());
        }

        [HttpPost]
        public IActionResult Insert(Materials materials)
        {
            using (SqlConnection connection = new SqlConnection(connectionString))
            {
                connection.Open();
                string query = "INSERT INTO Materials(name,unitOfMeasurement,count,cost) VALUES(@name,@unitOfMeasurement,@count,@cost)";
                using (SqlCommand command = new SqlCommand(query, connection))
                {
                    command.Parameters.AddWithValue("@name", materials.Name);
                    command.Parameters.AddWithValue("@unitOfMeasurement", materials.UnitId);
                    command.Parameters.AddWithValue("@count", materials.Count);
                    command.Parameters.AddWithValue("@cost", materials.Cost);
                    command.ExecuteNonQuery();
                }
            }
            return RedirectToAction("Index");
        }
        public IActionResult Edit(int id)
        {
            Materials materials = new Materials();
            using (SqlConnection connection = new SqlConnection(connectionString))
            {
                connection.Open();
                string query = "SELECT ID,name, unitOfMeasurement,count,cost FROM Materials WHERE ID=@Id";
                using (SqlCommand command = new SqlCommand(query, connection))
                {
                    command.Parameters.AddWithValue("@Id", id);
                    using (SqlDataReader reader = command.ExecuteReader())
                    {
                        if (reader.Read())
                        {
                            materials.Id = reader.GetInt32(0);
                            materials.Name = reader.GetString(1);
                            materials.UnitId = reader.GetInt32(2);
                            materials.Count = Math.Round(reader.GetDouble(3), 2);
                            materials.Cost = Math.Round(reader.GetDouble(4), 2);
                        }
                    }
                }

            }
            ViewBag.Units = GetUnits();
            return View(materials);
        }
        [HttpPost]
        public IActionResult Edit(Materials materials)
        {
            using (SqlConnection connection = new SqlConnection(connectionString))
            {
                connection.Open();
                string query = "UPDATE Materials SET name=@name, unitOfMeasurement=@unitOfMeasurement, count=@count, cost=@cost WHERE ID=@Id";
                using (SqlCommand command = new SqlCommand(query, connection))
                {
                    command.Parameters.AddWithValue("@Id", materials.Id);
                    command.Parameters.AddWithValue("@name", materials.Name);
                    command.Parameters.AddWithValue("@unitOfMeasurement", materials.UnitId);
                    command.Parameters.AddWithValue("@count", materials.Count);
                    command.Parameters.AddWithValue("@cost", materials.Cost);
                    command.ExecuteNonQuery();
                }
            }
            return RedirectToAction("Index");
        }
        public List<SelectListItem> GetUnits()
        {
            List<SelectListItem> units = new List<SelectListItem>();
            using (SqlConnection connection = new SqlConnection(connectionString))
            {
                connection.Open();
                string query = "SELECT ID,name FROM UnitsOfMeasurement";
                using (SqlCommand command = new SqlCommand(query, connection))
                using (SqlDataReader reader = command.ExecuteReader())
                {
                    while (reader.Read())
                    {
                        units.Add(new SelectListItem
                        {
                            Value = reader.GetInt32(0).ToString(),
                            Text = reader.GetString(1)
                        });
                    }
                }
            }
            return units;
        }
    }
}

Views/Materials/Edit.cshtml
@model Materials

<div class="conteiner">
    <h1>Редоктирование сырья</h1>
    <form asp-action="Edit" method="post">
        <input type="hidden" asp-for="Id" />

        <label>Название сырья</label>
        <input type="text" asp-for="Name" />
        <label>Единица измерения</label>
        <select asp-for="UnitId" asp-items="ViewBag.Units"></select>
        <label>Количество</label>
        <input type="text" asp-for="Count" />
        <label>Сумма</label>
        <input type="text" asp-for="Cost" />
        <div class="action">
            <button type="submit" class="btn_ad">Сохранить</button>
            <a href="@Url.Action("Index","Materials")" class="btn_bc">Вернуться</a>
        </div>
    </form>
</div>

<style>
    body{
        font-family:'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
        background-color: burlywood;
        margin: 0px;
        padding: 0px;
    }
    .conteiner{
        width: 60%;
        margin: 50px auto;
        background-color: antiquewhite;
        padding: 20px;
        border-radius: 8px;
        box-shadow: 0 4px 8px rgb(0,0,0,0.1);
        text-align:center;
    }
    form{
        display:flex;
        flex-direction: column;
        width: 45%;
        margin: 0 auto;
    }
    input,label,select{
        padding: 10px;
        margin-bottom: 10px;
        font-size: 16px;
    }
    input,select{
        box-shadow: 0 4px 8px rgba(0,0,0,0.1);
        border-radius: 5px;
        border: none;
    }
    .action{
        display:flex;
        justify-content: safe center;
        gap: 10px;
        margin-top: 15px;
        margin-bottom: 15px;
    }
    .btn_ad{
        background-color: greenyellow;
        color:gray;
        padding: 10px;
        border:none;
        border-radius: 5px;
        box-shadow: 0 4px 8px rgba(0,0,0,0.1);
    }

    .btn_bc {
        background-color: deepskyblue;
        color: black;
        padding: 10px;
        border: none;
        text-decoration: none;
        border-radius: 5px;
        box-shadow: 0 4px 8px rgba(0,0,0,0.1);
    }
</style>

Views/Materials/Index.cshtml
@model List<Практика.Models.Materials>
@{
    var user = Context.Session.GetInt32("Role");
}
<div class="conteiner">
    <h1>Сырье</h1>
    <div class="btn_action">
        @if (user == 3 || user == 2)
        {
            <a href="@Url.Action("Insert","Materials")" class="btn_ad">Добавить</a>
        }
        else
        {
            <a href="javascript:void(0)" class="btn_none">Добавить</a>
        }
        <a href="@Url.Action("Index","Home")" class="btn_bc">Вернуться</a>
    </div>
    <table class="table_data">
        <thead>
            <tr>
                <th>Название материала</th>
                <th>Единица иземерения</th>
                <th>Количество</th>
                <th>Цена</th>
                <th>Действие</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var materials in Model)
            {
                <tr>
                    <td>@materials.Name</td>
                    <td>@materials.Unit</td>
                    <td>@materials.Count</td>
                    <td>@materials.Cost</td>
                    <td>
                        <div class="action">
                            @if (user == 3 || user == 2)
                            {

                                <form method="post" action="/Materials/Delete/@materials.Id" onsubmit="return confirm('Вы уверены что хотите удалить?')">
                                    <button type="submit" class="btn_del">Удалить</button>
                                </form>
                                <form method="get" action="/Materials/Edit/@materials.Id">
                                    <button type="submit" class="btn_ed">Рекдоктировать</button>
                                </form>
                            }
                            else
                            {

                                <form>
                                    <button type="button" class="btn_none" disabled>Удалить</button>
                                </form>
                                <form>
                                    <button type="button" class="btn_none" disabled>Рекдоктировать</button>
                                </form>
                            }
                        </div>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

<style>
    body {
        font-family: Arial, Helvetica, sans-serif;
        background-color: #F9FAFB;
        margin: 0;
        padding: 0;
    }

    .conteiner {
        width: 70%;
        margin: 50px auto;
        padding: 15px;
        background-color: #FFFFFF;
        border-radius: 10px; /* скругление углов */
        box-shadow: 0px 4px 8px rgba(0, 0, 0, 0.1);
        text-align: center;
    }

    .table_data {
        width: 90%;
        margin: 0 auto;
    }

        .table_data th, .table_data td {
            border: 1px solid #dddddd;
            padding: 10px;
            text-align: center;
        }

        .table_data th {
            background-color: #f2f2f2;
            color: #333;
            font-weight: bold;
        }

    .action {
        display: flex;
        gap: 10px;
    }

    .btn_del {
        background-color: red;
        color: white;
        border: none;
        padding: 10px;
        border-radius: 5px;
    }

    .btn_ed {
        background-color: lime;
        color: black;
        border: none;
        padding: 10px;
        border-radius: 5px;
    }

    .btn_action {
        display: flex;
        justify-content: safe center;
        gap: 10px;
        margin-bottom: 10px;
    }

    .btn_ad {
        background-color: green;
        color: white;
        border: none;
        padding: 10px;
        text-decoration: none;
        border-radius: 5px;
    }

    .btn_bc {
        background-color: yellowgreen;
        color: white;
        border: none;
        padding: 10px 15px;
        text-decoration: none;
        border-radius: 5px;
    }

    .btn_none {
        padding: 12px;
        text-decoration: none;
        border-radius: 5px;
        background-color: gray;
        color: white;
        border: none;
        cursor: no-drop;
    }
</style>

Views/Materials/Insert.cshtml
@model Materials

<div class="conteiner">
    <h1>Добавление нового сырья</h1>
    <form asp-action="Insert" method="post">
        <label>Название сырья</label>
        <input type="text" asp-for="Name" required />
        <label>Единица измерения</label>
        <select asp-for="UnitId" asp-items="ViewBag.Units" required>
        <option>Выберите единицу измерения</option>
        </select>
        <label>Количество</label>
        <input type="text" asp-for="Count" value="0" required />
        <label>Сумма</label>
        <input type="text" asp-for="Cost" value="0" required />
        <div class="action">
        <button type="submit" class="btn_ad">Добавить</button>
        <a href="@Url.Action("Index", "Materials")" class="btn_bac">Вернуться</a>
        </div>
    </form>

</div>

<style>
    body{
        font-family:'Lucida Sans', 'Lucida Sans Regular', 'Lucida Grande', 'Lucida Sans Unicode', Geneva, Verdana, sans-serif;
        background-color:burlywood;
        margin:0;
        padding:0;
    }
    .conteiner{
        padding: 15px;
        width: 60%;
        margin: 50px auto;
        text-align:center;
        background-color:antiquewhite;
        border-radius: 5px;
        box-shadow: 0 4px 8px rgba(0,0,0,0.1);
    }
    form{
        width: 45%;
        margin: 0 auto;
        display: flex;
        flex-direction: column;

    }
    input,label,select{
        width: 100%;
        margin-bottom:10px;
        padding: 10px;
        font-size: 16px;
    }
    input,select{
        border-radius: 5px;
       box-shadow: 0 4px 8px rgba(0,0,0,0.1);
       border:none;

    }
   
    .action{
        display: flex;
        justify-content: safe center;
        gap: 10px;
        margin-top: 5px;
    }

    .btn_ad{
        padding: 10px;
        border-radius:5px;
        background-color: lawngreen;
        color: gray;
        border:none;

    }

    .btn_bac {
        padding: 10px;
        border-radius: 5px;
        background-color: lightyellow;
        color: gray;
        border: none;
        text-decoration: none;
    }
</style>